### ISSUE TITLE
Why not re-purpose ruby-vs-js-arrays to maintain history?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ruby-arrays#1]

**Comment by gaand** [comment]
@jrhorn424 and I talked about this and we've agreed to the creation of two repositories from one (ruby and ruby-vs-js-study) for this refactoring.

**Comment by neugierige** [comment]
Could we close this now?

**Comment by gaand** [comment]
I believe so.

@jrhorn424 Would you please close or comment further?  Thanks.

**Comment by gaand** [comment]
@jrhorn424 I'm closing.  If you believe this action is incorrect, please reopen.  Thanks.
